
name: Compile server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install bam
        run: 
          sudo apt update
          sudo apt install git libfreetype6-dev libsdl2-dev libpnglite-dev libwavpack-dev python3 build-essential cmake libicu-dev -y
          git clone https://github.com/teeworlds/Bam
          cd Bam
          git checkout v0.4.0
          ./make_unix.sh
          mv bam ../
          cd ..
          ./bam server_release

      - name: Compile binary server file
        run: bam server_release

      - name: Test running
        run: |
            ./xPanic-Server exec autoexec_server.cfg.example;sv_name GitHub Test xPanic Server;
